server:
  port: 4001

spring:
  messages:
    basename: messages
  autoconfigure:
    #自动化配置 例外处理
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  # dynamic-datasource-spring-boot-starter 动态数据源的配置内容
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master # 设置默认的数据源或者数据源组，默认值即为 master
      datasource:
        # test 数据源配置
        master:
          name: druidDataSource
          type: com.alibaba.druid.pool.DruidDataSource
          driverClassName: oracle.jdbc.driver.OracleDriver
          #你自己的数据库IP地址和数据库名，账号以及密码
          url: jdbc:oracle:thin:@//192.168.0.160:1521/szmsa
          username: msacp
          password: msacp
        # test1 数据源配置
        test1:
          url: jdbc:oracle:thin:@//192.168.0.160:1521/szmsa
          driver-class-name: oracle.jdbc.driver.OracleDriver
          username: szmsa
          password: szmsa

      #dynamic - 公共配置
      druid:
        initialSize: 5
        minIdle: 5
        maxActive: 30
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT * FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j,config
        useGlobalDataSourceStat: true
        stat:
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 10000

  redis:
    host: 192.168.0.166
    port: 6379
    password: msaredis
    lettuce:
      pool:
        max-wait: 100000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8       # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
        max-active: 20    # 连接池最大连接数（使用负值表示没有限制）
    timeout: 5000         # 连接超时时间（毫秒）


mybatis-plus:
  type-aliases-package: cc.winfo.*
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #字段名称可以驼峰映射

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cc.winfo.*

swagger:
  title: 示例模块
  license: Powered By ruoyi
  licenseUrl: http://localhost:4001/api/
#  enabled: true